export type Term = { term: string; definition: string };

export const glossary: Term[] = [
  { term: "Amortization", definition: "The total time it would take to pay off your mortgage in full at the current payment, commonly 25 or 30 years. Longer amortizations lower the payment but increase total interest." },
  { term: "Appraisal", definition: "A lender-ordered valuation of the property by a licensed appraiser. The lender bases the mortgage on the lower of the purchase price and the appraised value." },
  { term: "B lender / alternative lender", definition: "A lender with more flexible qualifying rules than the major banks, often used for self-employed borrowers, bruised credit, or unusual properties, usually at a higher rate or with a fee." },
  { term: "Blend and extend", definition: "Renegotiating your mortgage mid-term by blending your current rate with a new rate over a new, longer term, typically to avoid a full prepayment penalty." },
  { term: "Bridge financing", definition: "A short-term loan that covers the gap when your new home closes before your current one sells." },
  { term: "Closed mortgage", definition: "A mortgage that limits how much you can prepay during the term. Closed mortgages have lower rates than open ones; most prepayment privileges still allow 10% to 20% per year." },
  { term: "Closing costs", definition: "One-time costs paid on the day you take ownership: land transfer tax, legal fees, title insurance, adjustments, and PST on any insurance premium. Budget 1.5% to 4% of the price." },
  { term: "Collateral charge", definition: "A way of registering a mortgage that can secure more than the initial loan, making it easier to borrow more later but harder to switch lenders at renewal without legal fees." },
  { term: "Conventional mortgage", definition: "A mortgage with a down payment of 20% or more, which does not require default insurance." },
  { term: "Default insurance", definition: "Insurance (from CMHC, Sagen, or Canada Guaranty) required when the down payment is under 20%. It protects the lender, and its premium is added to your mortgage." },
  { term: "Down payment", definition: "The portion of the purchase price you pay up front. The minimum is 5% of the first $500,000 and 10% of the remainder up to the insured cap, and 20% above it." },
  { term: "FHSA (First Home Savings Account)", definition: "A registered account that combines a tax deduction on contributions with tax-free withdrawals toward a first home." },
  { term: "Fixed rate", definition: "An interest rate that stays the same for the whole term, so your payment doesn't change." },
  { term: "GDS ratio (gross debt service)", definition: "Housing costs (mortgage payment, property tax, heat, half of condo fees) as a percentage of gross income. Lenders typically cap it at 39%." },
  { term: "HELOC (home equity line of credit)", definition: "A revolving line of credit secured by your home, usually up to 65% of its value on its own or 80% combined with a mortgage. You pay interest only on what you use." },
  { term: "High-ratio mortgage", definition: "A mortgage with less than 20% down, which must be default-insured." },
  { term: "Home Buyers' Plan (HBP)", definition: "A federal program that lets first-time buyers withdraw from their RRSP for a down payment and repay it over 15 years." },
  { term: "Interest rate differential (IRD)", definition: "A prepayment penalty on fixed-rate mortgages based on the difference between your rate and the lender's current rate for the remaining term. It can be much larger than three months' interest." },
  { term: "Land transfer tax", definition: "A provincial tax on the purchase price paid at closing. Toronto adds a municipal tax on top. First-time buyers get partial rebates on both." },
  { term: "Loan-to-value (LTV)", definition: "The mortgage amount as a percentage of the property value. An 80% LTV means 20% equity." },
  { term: "Maturity date", definition: "The date your current term ends and the mortgage must be renewed, paid out, or switched." },
  { term: "Monoline lender", definition: "A lender that only does mortgages, with no branches or chequing accounts. Often competitive on rate and fairer on penalties." },
  { term: "Open mortgage", definition: "A mortgage you can pay off at any time without penalty, in exchange for a higher rate. Useful for short holds." },
  { term: "Porting", definition: "Moving your existing mortgage, with its rate and terms, to a new property when you move, avoiding a penalty." },
  { term: "Posted rate", definition: "A lender's published rate, usually higher than what is actually offered. Some penalties are calculated using posted rates." },
  { term: "Pre-approval", definition: "A lender's review of your income, credit, and down payment that sets a maximum mortgage and holds a rate, typically for 120 days." },
  { term: "Prepayment privileges", definition: "The amount you can pay above your regular payments each year without penalty, commonly 10% to 20% of the original principal plus a payment increase." },
  { term: "Prime rate", definition: "The benchmark rate lenders use for variable-rate mortgages and lines of credit. It moves with the Bank of Canada's policy rate." },
  { term: "Rate hold", definition: "A lender's guarantee of a rate for a set period, so you're protected if rates rise before you close." },
  { term: "Readvanceable mortgage", definition: "A mortgage paired with a HELOC where the credit limit grows as you pay down principal." },
  { term: "Refinance", definition: "Replacing your mortgage with a new one to change the amount, rate, or terms, usually to access equity or consolidate debt. Limited to 80% of the home's value." },
  { term: "Renewal", definition: "Signing a new term with your current lender when the old one matures. You can also switch to another lender at this point, often at no cost." },
  { term: "Stress test (minimum qualifying rate)", definition: "The rule that federally regulated lenders must qualify you at the higher of your contract rate plus 2% or 5.25%. It limits how much you can borrow, not what you pay." },
  { term: "Switch / transfer", definition: "Moving your mortgage to a new lender at renewal without changing the amount or amortization. The new lender often covers the costs." },
  { term: "TDS ratio (total debt service)", definition: "Housing costs plus all other debt payments as a percentage of gross income. Lenders typically cap it at 44%." },
  { term: "Term", definition: "The length of your current mortgage contract, commonly 1 to 5 years. At the end of the term you renew, not pay off." },
  { term: "Title insurance", definition: "A one-time policy that protects you and your lender against title defects, fraud, and survey issues. Most lenders require it." },
  { term: "Variable rate", definition: "A rate that moves with the lender's prime rate. Payments may stay fixed while the interest portion changes, or adjust with the rate, depending on the product." },
];
